CREATE USER IF NOT EXISTS 'replica'@'%'
IDENTIFIED BY 'replica123';

ALTER USER 'replica'@'%'
IDENTIFIED BY 'replica123';

GRANT REPLICATION SLAVE, REPLICATION CLIENT
ON *.*
TO 'replica'@'%';

FLUSH PRIVILEGES;

