STOP REPLICA;
RESET REPLICA ALL;

CHANGE REPLICATION SOURCE TO
    SOURCE_HOST='${NEW_MASTER}',
    SOURCE_PORT=3306,
    SOURCE_USER='replica',
    SOURCE_PASSWORD='replica123',
    SOURCE_AUTO_POSITION=1;

START REPLICA;

